[phases.setup]
nixPkgs = ['nodejs_22', 'npm-9_x']

[phases.install]  
cmds = ['npm ci']

[phases.build]
cmds = [
  'mkdir -p data',
  'npm run build',
  'DATABASE_URL="file:./data/data.db" npx prisma generate'
]

[start]
cmd = 'npm start'